name: Trigger ReviewBot

on:
  pull_request:
    branches:
      - main

jobs:
  trigger-reviewbot:
    runs-on: ubuntu-latest
    steps:
      - name: Call ReviewBot Webhook
        run: |
          curl -X POST "https://d3cb-112-221-79-74.ngrok-free.app/api/webhook" \
               -H "Content-Type: application/json" \
               -d '${{ toJson(github.event) }}'
