name: Trigger ReviewBot

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  trigger-reviewbot:
    runs-on: ubuntu-latest
    steps:
      - name: Call ReviewBot Webhook
        run: |
          curl -X POST "https://62dc-112-221-79-74.ngrok-free.app/api/webhook" \
               -H "Content-Type: application/json" \
               -d '{
                 "repository": "${{ github.repository }}",
                 "pull_request": {
                   "number": "${{ github.event.pull_request.number }}",
                   "diff_url": "${{ github.event.pull_request.diff_url }}"
                 }
               }'
