name: Trigger ReviewBot

on:
  pull_request:
    branches:
      - main

jobs:
  trigger-reviewbot:
    runs-on: ubuntu-latest
    steps:
      - name: Call ReviewBot Webhook
        run: |
          curl -X POST "http://13.125.171.105:8080/api/webhook" \
               -H "Content-Type: application/json" \
               -d '${{ toJson(github.event) }}'
